services:
  server:
    image: jekyll/jekyll:4.2.2
    container_name: a04t
    environment:
      MY_ENV_VAR_DUMMY: 'service_named_server'
    volumes:
      - '../.:/srv/jekyll' # relative path from this folder
    ports:
      - 9999:4000 # (localhost port) => (docker port)
    command: sh "docker/docker-compose.sh"
